name: Normal deployement

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: app
      MIX_ENV: prod
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.PRODUCTION_HOST }}
          SSH_USER: ${{ secrets.PRODUCTION_USERNAME }}
          SSH_KEY: ${{ secrets.PRODUCTION_KEY }}

      - name: Prepare build environment
        run: |
          ssh production "mkdir -p /root/build"
          ssh production "mkdir -p /root/app"
          echo "BUILD_DIR=/root/build" >> $GITHUB_ENV
          echo "APP_DIR=/root/app" >> $GITHUB_ENV

      - name: Deploy to production
        run: |
          rsync -ahz --delete . production:${BUILD_DIR}

      - name: mix deps.get
        run: |
          ssh production "cd ${BUILD_DIR} && mix deps.get"

      - name: mix compile
        run: |
          ssh production "cd ${BUILD_DIR} && mix compile"

      - name: mix distillery.release
        run: |
          ssh production "cd ${BUILD_DIR} && mix distillery.release"
