name: Normal deployement
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: app
      MIX_ENV: prod
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - name: Deploy
        run: |
          echo ${{ github.workspace }}
